const ci = T.q('#sec-CI');
const sd = T.input(ci, 'Start Date'), ed = T.input(ci, 'End Date');
const setDate = (el, v) => T.date(el, v);
await setDate(sd, '06/10/2026');
await setDate(ed, '31/12/2026');
T.text(ci, 'URL slug', 'tax-fighter-10-10-test');
const out = {};
out.categoryOptions = await T.options(T.q('app-select-field p-select', ci));
await T.pick(T.q('app-select-field p-select', ci), 'ประกันสะสมทรัพย์');
out.slugLabel = T.norm(T.qa('label', ci).find((l) => l.textContent.includes('URL slug'))?.textContent);
T.text(ci, 'ลำดับแสดงผล', '1');
T.text(ci, 'SEO title', 'Tax Fighter 10/10 — ประกันลดหย่อนภาษี');
T.text(ci, 'SEO description', 'ประกันออมทรัพย์ 10 ปี จ่าย 10 ปี ลดหย่อนภาษีได้สูงสุด 100,000 บาท (ข้อความทดสอบ)');
const ms = T.qa('app-multiselect-field p-multiselect', ci);
await T.pickMulti(ms[0], ['โรคร้ายแรง']);
await T.pickMulti(ms[1], ['ลดหย่อนภาษี', 'จ่ายสั้น คุ้มครองยาว']);
out.chips = ms.map((m) => T.qa('.p-multiselect-chip, .p-chip', m).map((c) => T.norm(c.textContent)));
out.values = { start: sd.value, end: ed.value };
T.closeToasts(); await T.wait(300);
T.button('Save').click(); await T.wait(3000);
out.toasts = T.toasts();
T.scrollTo('#sec-CI');
return out;
